import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Lato } from "next/font/google"
import NavBar from "./components/navBar"

const lato = Lato({ 
  weight: "400",
  display: "swap",
  subsets: ["latin"]
});

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
})
{



  return (

    <html lang="en">
    <head>
      <script type="text/javascript" src="https://cdn.addevent.com/libs/atc/1.6.1/atc.min.js" async defer></script>
    </head>
      <body className={lato.className + " min-h-screen scroll-smooth"}>
      <h1 className="z-30 w-full tracking-wider text-2xl bg-white sm:bg-opacity-60 mx-auto text-center pt-6 pb-4 hidden sm:block sm:pb-0 drop-shadow-md">M'KENNA & PATRICK</h1>
      <NavBar/>
        {children}
        </body>
    </html>
  )
}
