import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Lato } from "next/font/google"
import Nav from "./components/nav"

const lato = Lato({ 
  weight: "400",
  display: "swap",
  subsets: ["latin"]
});

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
})
{



  return (
    <html lang="en">
      <body className={lato.className + " min-h-screen"}>
      <h1 className="w-full tracking-wider text-2xl bg-white bg-opacity-60 mx-auto text-center pt-6">M'KENNA & PATRICK</h1>
        <nav className="sticky top-0 w-full mx-auto z-30 bg-white bg-opacity-60 backdrop-blur-lg pb-4">
          <br />
           <Nav/>
            {/* <a className="hover:underline underline-offset-8" href="/">Home</a>
            |
            <a className="hover:underline underline-offset-8" href="/party">Wedding Party</a>
            |
            <a className="hover:underline underline-offset-8" href="/schedule">Schedule</a>
            |
            <a className="hover:underline underline-offset-8" href="/gallery">Gallery</a>
            |
            <a className="hover:underline underline-offset-8" href="/rsvp">RSVP</a> */}
          </nav>
        {children}
        </body>
    </html>
  )
}
